name: Build and Test .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restaurar pacotes
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Rodar testes
      run: dotnet test --no-build --verbosity normal

    - name: Publicar
      run: dotnet publish --configuration Release --output ./build